---
title: "Chi sq. Graphic"
author: "Katie Munteanu"
date: "2024-05-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressWarnings(library(ggplot2))
suppressWarnings(library(cowplot))
english_data <- read.csv("English_Data_Clean.csv")

english_data$interval <- factor(ifelse(english_data$interval, "In Interval", "Out of Interval"))
english_data$accurate <- factor(ifelse(english_data$accurate, "Accurate", "Inaccurate"))
english_data$accurate <- factor(english_data$accurate, levels = c("Inaccurate", "Accurate"))
```

```{r}
custom_colors <- c("Accurate" = "lightgreen", "Inaccurate" = "lightcoral")

p <- ggplot(english_data, aes(fill = accurate, x = interval, y = AWPE)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(x = "Interval Category", y = "Proportion of AWPE scores", fill = "Category") +
  theme_minimal() + 
  scale_fill_manual(values = custom_colors)

p_value <- 6.114063e-06

p_annotated <- ggdraw() +
  draw_plot(p) + 
  draw_text(
    paste("P-Value =", format(p_value, digits = 2, scientific = TRUE)),
    x = .9, y = .8, size = 12, hjust = 0.5
  )

p_annotated
```

```{r}
x_breaks <- seq(25, 45, by = 5)

ggplot(english_data, aes(x = AWPE, fill = interval, color = interval, y = ..count../sum(..count..))) +
  geom_histogram(binwidth = 1, position = "identity", alpha = 0.25, size = 0.5) + 
  scale_fill_manual(values = c("TRUE" = "lightgreen", "FALSE" = "pink")) +
  scale_color_manual(values = c("TRUE" = "lightgreen", "FALSE" = "pink")) +
  labs(title = "Histogram of AWPE Scores Based on Interval",
       x = "AWPE",
       y = "Proportion of AWPE Scores",
       fill = "Within Interval",
       color = "Within Interval") + 
  scale_x_continuous(breaks = x_breaks) +  
  theme_minimal()
```
```{r}
ggplot(english_data, aes(AWPE, y = 0, color = interval)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("TRUE" = "lightgreen", "FALSE" = "pink")) +
  labs(title = "Number Line of AWPE Scores",
       x = "AWPE",
       y = NULL, 
       color = "Within Interval") +  # setting y label to NULL to remove it
  theme_minimal() +
  geom_text(data = data.frame(x = c(25, 30, 35, 40, 45), label = c("25", "30", "35", "40", "45")), aes(x = x, label = label), vjust = -0.7, color = "black", size = 3.25) + theme(legend.position = c(.92, .7))

```




